### ISSUE TITLE
Rmysql failing during PDF render

### ISSUE THREAD

**Issue by seltmann** [seltmann/ttdtcn-report#1]
When producing rendered pdf rmarkdown the render fails if I am querying from a large table. But the error sounds like it is due to rendering underscores, a reserved character in latex. Rendering in word is fine. @fmichonneau have you come across the same issue? Tables with 30k work fine, tables with half million fail.

**Comment by fmichonneau** [comment]
try to add:

```
counts <- dbFetch(total)
```
after `total <- dbGetQuery(connection, "Select count(*) from Projects")`

and then inline in your document: `r counts`. I think you always need to use the fetch command after calling a query. I'm not sure why you'd get underscores in your return value after using count.

**Comment by seltmann** [comment]
@fmichonneau thank you for the help. Here is the specific error, which made me think that its a missing character issue. Will try what you suggest and report back!

"pandoc: Error producing PDF from TeX source.
! Missing $ inserted.
<inserted text> 
                $
l.67 Database for the project: 1.589257\times

Error: pandoc document conversion failed with error 43
Execution halted"

**Comment by seltmann** [comment]
@fmichonneau 
I tried what you suggested and go the error: could not find function dbfetch. I dont think I need dbfetch because when I use Rmysql outside of Rmarkdown (just in R) I have no issues and never use dbfetch. 

I did find that in rmarkdown if I add results results='asis' to the block I can print the results. See results in generalReport.pdf (count(*) 1 1589257) and code in generalReport.Rmd

Thank you! ahead of time for any further suggestions

**Comment by fmichonneau** [comment]
I'm not sure what's going on. knitr is really smart about escaping characters. Can you include in the repo the script that you call (mysqlConnect-function.R) and maybe also the database (or put it in Dropbox) so I can try to see the whole thing? thanks!

**Comment by seltmann** [comment]
Issue was the output as scientific notation. as.integer(total); before render corrected the problem.
